name: CI Pipeline
run-name: ${{ gitea.actor }} triggered CI pipeline

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix: { node-version: [18, 20] }
    env:
      NODE_OPTIONS: "--max_old_space_size=4096"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
      - run: npm ci
      - run: npm test

      # If the Codecov Action fails on Gitea, replace this with the bash uploader below
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage/lcov.info
          flags: unittests

      # Bash uploader alternative (uncomment if the action above has issues)
      # - name: Upload coverage to Codecov (bash)
      #   run: |
      #     curl -s https://codecov.io/bash > codecov.sh
      #     bash codecov.sh -t "${{ secrets.CODECOV_TOKEN }}" -f coverage/lcov.info -F unittests

  e2e:
    runs-on: ubuntu-latest
    strategy:
      matrix: { browser: [chromium, firefox, webkit] }
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: 20, cache: npm }
      - run: npm ci
      - run: npx playwright install --with-deps ${{ matrix.browser }}
      - run: npm run build

      # start app, wait, run tests
      - run: npm run preview &
        env: { CI: true }
      - run: npx wait-on http://localhost:3000
      - run: npx playwright test --project=${{ matrix.browser }}
        env: { CI: true }

      # package artifacts (keeps file count small)
      - name: Package E2E artifacts
        if: always()
        run: |
          tar -czf playwright-${{ matrix.browser }}.tgz playwright-report test-results || true

      - name: Upload E2E artifacts
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: playwright-results-${{ matrix.browser }}
          path: playwright-${{ matrix.browser }}.tgz
          retention-days: 30

  visual-regression:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: 20, cache: npm }
      - run: npm ci
      - run: npx playwright install --with-deps
      - run: npm run build
      - run: npm run preview &
        env: { CI: true }
      - run: npx wait-on http://localhost:3000

      # Seed snapshots on main branch only (one-time setup)
      - name: Seed snapshots (main only)
        if: github.ref == 'refs/heads/main'
        run: PLAYWRIGHT_UPDATE_SNAPSHOTS=1 npx playwright test tests/e2e/visual-regression.spec.ts --project=chromium
        env: { CI: true }

      # Run visual regression tests
      - name: Run visual regression tests
        run: npx playwright test tests/e2e/visual-regression.spec.ts
        env: { CI: true }

      - name: Package visual artifacts
        if: always()
        run: |
          tar -czf visual-regression.tgz test-results tests/e2e/visual-regression.spec.ts-snapshots || true

      - name: Upload visual artifacts
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: visual-regression-results
          path: visual-regression.tgz
          retention-days: 30

  performance:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: 20, cache: npm }
      - run: npm ci
      - run: npm run build
      - run: npm run preview &
        env: { CI: true }
      - run: npx wait-on http://localhost:3000
      - run: npm run lhci
        env: { CI: true }

  storybook:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: 20, cache: npm }
      - run: npm ci
      - run: npm run build-storybook
      - run: npm run test:sb
        env: { CI: true }

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: 20, cache: npm }
      - run: npm ci
      - run: npm run lint
      - run: npx prettier --check "**/*.{js,jsx,ts,tsx,json,css,md}"

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: 20, cache: npm }
      - run: npm ci
      - run: npm run build
      - run: npm run build-storybook
